# Generated by Django 4.2.1 on 2023-08-02 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anneescolaire', models.CharField(max_length=100)),
                ('annee_debut', models.DateField()),
                ('annee_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_classe', models.CharField(max_length=150)),
                ('code_classe', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_departement', models.CharField(max_length=100)),
                ('code_departement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_filiere', models.CharField(max_length=200)),
                ('code_filiere', models.CharField(max_length=100)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_semestre', models.CharField(choices=[('semestre1', 'semestre1'), ('semestre2', 'semestre2'), ('semestre3', 'semestre3'), ('semestre4', 'semestre4'), ('semestre5', 'semestre5'), ('semestre6', 'semestre6')], max_length=100)),
                ('code_semestre', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, null=True)),
                ('prenom', models.CharField(max_length=150, null=True)),
                ('telephone', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('adresse', models.CharField(max_length=150, null=True)),
                ('adresse_physique', models.CharField(max_length=150, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image_tuteur/')),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_specialite', models.CharField(blank=True, max_length=200, null=True)),
                ('code_specialite', models.CharField(blank=True, max_length=150, null=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_niveau', models.CharField(choices=[('Licence1', 'Licence1'), ('Licence2', 'Licence2'), ('Licence3', 'Licence3')], max_length=150)),
                ('code_niveau', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3')], max_length=150)),
                ('anneeScolaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.anneescolaire')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(blank=True, max_length=200)),
                ('code_matiere', models.CharField(blank=True, max_length=50, null=True)),
                ('nature_ue', models.CharField(blank=True, max_length=50, null=True)),
                ('code_ue', models.CharField(blank=True, max_length=50, null=True)),
                ('coefficient_matiere', models.DecimalField(decimal_places=2, help_text="s'il vous entrer un nombre qui est valide", max_digits=4)),
                ('horaire', models.IntegerField()),
                ('filMatiere', models.ManyToManyField(to='students.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.niveau')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.semestre')),
                ('specialite', models.ManyToManyField(to='students.specialite')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_etudiant', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('nom', models.CharField(blank=True, max_length=150)),
                ('prenom', models.CharField(blank=True, max_length=150)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(blank=True, max_length=150)),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='image_etudiant/')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=150, null=True)),
                ('regime', models.CharField(blank=True, choices=[('normal', 'Normal'), ('special', 'Special')], max_length=150, null=True)),
                ('inscription', models.CharField(blank=True, choices=[('OUI', 'INSCRIT(E)'), ('NON', 'NON INSCRIT(E)')], max_length=150, null=True)),
                ('anneeScolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.anneescolaire')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.filiere')),
                ('niveau', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='students.niveau')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.specialite')),
                ('tuteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.tuteur')),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=150, null=True)),
                ('prenom', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.IntegerField()),
                ('adresse', models.CharField(blank=True, max_length=150, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=150, null=True)),
                ('grade', models.CharField(choices=[('Docteur', (('D', 'Missionnaire'), ('P', 'permanent'), ('V', 'Vacateur'))), ('Ingenieur', (('D', 'Missionnaire'), ('P', 'permanent'), ('V', 'Vacateur')))], max_length=150)),
                ('diplome', models.CharField(choices=[('Doctorat', 'Doctorat'), ('Master', 'Master'), ('Licence', 'Licence')], max_length=150)),
                ('photo', models.ImageField(upload_to='image_enseignant/')),
                ('anneeScolaire', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='students.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classroom')),
                ('matiere', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='students.matiere')),
                ('niveau', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='students.niveau')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.semestre')),
            ],
        ),
    ]
