# Generated by Django 4.2.1 on 2023-08-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='nom_filiere',
            field=models.CharField(choices=[('D.A.W.M', 'D.A.W.M'), ('A.S.R.S', 'A.S.R.S')], max_length=200),
        ),
    ]
