# Generated by Django 4.2.1 on 2023-09-13 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_filiere_nom_filiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='niveau',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.semestre'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='code_filiere',
            field=models.CharField(choices=[('D.A.W.M', 'D.A.W.M'), ('A.S.R.S', 'A.S.R.S')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='nom_filiere',
            field=models.CharField(choices=[('Développement des applications web et mobiles', 'Dévelppement'), ('Administrations, sécurité de réseaux et des systèmes', 'Administration')], max_length=200, unique=True),
        ),
    ]
