# Generated by Django 4.2.1 on 2023-09-19 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_etudiant_niveau_etudiant_semestre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('TP', 'TP'), ('CONTOLE', 'CONTROLE'), ('EXAMEN', 'EXAMEN')], max_length=150)),
                ('note', models.DecimalField(decimal_places=2, max_digits=2)),
                ('etudiant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='students.etudiant')),
                ('matiere', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='students.matiere')),
            ],
        ),
    ]
