# Generated by Django 4.2.1 on 2023-09-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='types',
        ),
    ]
