# Generated by Django 4.2.1 on 2023-09-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_note_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='type_note',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
