# Generated by Django 4.1.5 on 2023-09-28 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_note_type_note_alter_note_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='niveau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.niveau'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.niveau'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.semestre'),
        ),
        migrations.AlterField(
            model_name='note',
            name='type_note',
            field=models.CharField(max_length=100),
        ),
    ]
