# Generated by Django 4.2.1 on 2023-09-30 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_semestre_niveau_alter_matiere_niveau_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_emplois', models.CharField(choices=[('Cours', 'Cours'), ('Examen Terminal', 'Examen Terminal'), ('Contrôle continu', 'Contrôle continu'), ('TP', 'TP')], max_length=150)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.enseignant')),
                ('filiere', models.ManyToManyField(to='students.filiere')),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.matiere')),
                ('niveau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.niveau')),
                ('semestre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.semestre')),
            ],
        ),
    ]
