# Generated by Django 4.2.1 on 2023-09-30 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_emplois'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplois',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='emplois',
            name='date_fin',
        ),
        migrations.AddField(
            model_name='emplois',
            name='annee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.anneescolaire'),
        ),
        migrations.AddField(
            model_name='emplois',
            name='date',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
