# Generated by Django 4.2.1 on 2023-09-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_remove_emplois_date_debut_remove_emplois_date_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplois',
            name='filiere',
        ),
        migrations.AddField(
            model_name='emplois',
            name='status',
            field=models.CharField(choices=[('TRONC COMMUN', 'TRONC COMMUN'), ('D.A.W.M', 'D.A.W.M'), ('A.S.R.S', 'A.S.R.S')], max_length=150, null=True),
        ),
    ]
