# Generated by Django 4.2.1 on 2023-09-30 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_remove_emplois_filiere_emplois_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplois',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.classroom'),
        ),
        migrations.AlterField(
            model_name='emplois',
            name='status',
            field=models.CharField(choices=[('D.A.W.M & A.S.R.S', 'D.A.W.M & A.S.R.S'), ('D.A.W.M', 'D.A.W.M'), ('A.S.R.S', 'A.S.R.S')], max_length=150, null=True),
        ),
    ]
