# Generated by Django 4.2.1 on 2023-10-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_emplois_classe_alter_emplois_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplois',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='emplois',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='emplois',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='emplois',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='emplois',
            name='semestre',
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='grade',
            field=models.CharField(choices=[('Docteur', (('Docteur', 'Missionnaire'), ('Permenant', 'permanent'), ('Vacateur', 'Vacateur'))), ('Ingenieur', (('D', 'Missionnaire'), ('P', 'permanent'), ('V', 'Vacateur')))], max_length=150),
        ),
    ]
