# Generated by Django 4.2.1 on 2023-10-03 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_remove_emplois_annee_remove_emplois_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplois',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.enseignant'),
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='specialite',
        ),
        migrations.AlterField(
            model_name='matiere',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.niveau'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.semestre'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='anneeScolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='note',
            name='etudiant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='students.etudiant'),
        ),
        migrations.AlterField(
            model_name='note',
            name='matiere',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='students.matiere'),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='niveau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.niveau'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='specialite',
            field=models.ManyToManyField(to='students.specialite'),
        ),
    ]
