# Generated by Django 4.1.5 on 2023-10-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_emplois_enseignant_remove_etudiant_specialite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneescolaire',
            name='annee_debut',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='anneescolaire',
            name='annee_fin',
            field=models.CharField(max_length=150),
        ),
    ]
