# Generated by Django 4.2.1 on 2023-10-08 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_alter_anneescolaire_annee_debut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departement',
            old_name='code_departement',
            new_name='code_section_sco',
        ),
        migrations.RenameField(
            model_name='departement',
            old_name='nom_departement',
            new_name='nom_section_sco',
        ),
    ]
