# Generated by Django 4.2.1 on 2023-10-08 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_rename_code_departement_departement_code_section_sco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(max_length=150, null=True)),
                ('anneeScolaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.anneescolaire')),
            ],
        ),
    ]
