# Generated by Django 4.2.1 on 2023-10-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_du_jour',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
