# Generated by Django 4.2.1 on 2023-10-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_comment_date_du_jour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='anneeScolaire',
            new_name='annee_universitaire',
        ),
    ]
