# Generated by Django 4.2.5 on 2023-09-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0006_alter_video_time_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profession',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
