# Generated by Django 4.2.5 on 2023-09-14 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0010_alter_course_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.lesson')),
            ],
        ),
    ]
